# Generated by Django 4.0.2 on 2022-04-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postedjobs',
            name='userlink',
        ),
    ]
